Implement `--version` arg
Arnau478/hevi pull request #13
Opened 2024-04-30 20:57 UTC by Reokodoku

**This PR adds the `--version` argument** (as well as `-v`) **to get information about the version of hevi built.**

---

When git is available, the build system tries to get the information to generate the version string from
`git describe --tags`. The format of the version taken from git is `x.x.x-dev.n+h`, where `n` is the commit number (starting with the last tag) and where `h` is the hash of the last commit.

If git is unavailable or an error occurs, the version string defaults to the one written in `build.zig`.

Also, the version is not taken from `build.zig.zon` because there is no function or variable to get it from there (the only way is to parse the zon file, but I don't think that is necessary).

2024-04-30 21:46 UTC, Arnau478 requested changes

2024-04-30 21:46 UTC, Arnau478 commented on build.zig
> +const VERSION = "1.0.0";
I don't think this is the right approach. Instead of using a string, we should use a [semver](https://semver.org/), which zig conveniently implements in the std.

2024-04-30 21:46 UTC, Arnau478 commented on build.zig
> +    }, "\n\r");
`b.runAllowFail` is not meant to be used like that. Instead, we should use `b.addSystemCommand`, which creates a `Step.Run`. Then, the arguments should be added with `cmd.addArg`. That's much safer than to just run a string as argv.

2024-04-30 21:50 UTC, Arnau478 commented
> Also, the version is not taken from build.zig.zon because there is no function or variable to get it from there (the only way is to parse the zon file, but I don't think that is necessary).

As a side note, I was actually considering doing that, as parsing it would be pretty easy. Also, https://github.com/ziglang/zig/issues/14531 won't be implemented until zig 0.14.0, so...

2024-05-01 09:32 UTC, Reokodoku commented on build.zig
> +    }, "\n\r");
I tried to use `b.addSystemCommand` but the result is something like
```zig
const git_run = b.addSystemCommand(&.{"git"});
git_run.addArg("describe");
git_run.addArg("--tags");
git_run.addArg("--abbrev=10");

const git_output_stdout = git_run.captureStdOut();
b.getInstallStep().dependOn(&b.addInstallFile(git_output_stdout, "../../zig-cache/git.txt").step);

// And then read the file
```

Either I am wrong or I think `b.runAllowFail` is better, because we get stdout directly and we don't need to write and read a file.

2024-05-01 09:33 UTC, Arnau478 commented on build.zig.zon
> +    .version = "1.0.0",
Why exactly did you do this? 1.0.0 hasn't released yet

2024-05-01 09:40 UTC, Reokodoku commented on build.zig.zon
> +    .version = "1.0.0",
The reason is that when you build the project you get the version from git tags. If the latest commit isn't tagged, the version is automatically `x.x.x-dev.`...

If it's wrong I can undo the change and in `build.zig` parse the string for remove `-dev`.

2024-05-01 09:46 UTC, Arnau478 commented on build.zig.zon
> +    .version = "1.0.0",
Oh, that makes sense...

2024-05-01 09:47 UTC, Arnau478 commented on build.zig
> +    }, "\n\r");
Yeah, it seems like a zig issue...

2024-05-01 11:01 UTC, Arnau478 commented
Looks pretty good to me. Just a small thing: when `git` is not available, it builds with the version being the one in `build.zig.zon` (no `-dev`) or anything. Sure, it cannot get the commit number nor id, but it can add a single `-dev`, to make it clear that it's not a release build.

2024-05-01 15:04 UTC, Arnau478 approved these changes
Looks good to me!

2024-05-01 15:04 UTC, merged