Add `--parser` arg
Arnau478/hevi pull request #21
Opened 2024-05-10 21:08 UTC by Reokodoku

This commit adds `--parser` argument to specify which parser to use to read the file.

This is only an arg. There isn't any field in the config file to set a specific parser.

2024-05-11 21:05 UTC, Arnau478 requested changes

2024-05-12 08:02 UTC, Arnau478 requested changes

2024-05-12 08:02 UTC, Arnau478 commented on src/parser.zig
> +                }
This will panic. Could you add an else statement that prints an error?

2024-05-12 08:36 UTC, Reokodoku commented on src/parser.zig
> +                }
Is something like this okay? Maybe we can print it in red (if color support is enabled).
```patch
diff --git a/src/parser.zig b/src/parser.zig
index da609ba..b41498c 100644
--- a/src/parser.zig
+++ b/src/parser.zig
@@ -21,6 +21,9 @@ pub fn getColors(allocator: std.mem.Allocator, reader: std.io.AnyReader, options
                 if (parser.matches(data)) {
                     parser.getColors(colors, data);
                     return colors;
+                } else {
+                    std.debug.print("The specified parser doesn't match the file format!\n", .{});
+                    std.process.exit(1);
                 }
             }
         } else if (parser.matches(data)) {
```

2024-05-12 08:42 UTC, Arnau478 commented on src/parser.zig
> +                }
Yeah, just do that. Maybe wirh an "Error:" prefix. I wanted to unify error reporting, but haven't done so yet. When I do I'll update it :)

2024-05-12 09:34 UTC, Arnau478 approved these changes

2024-05-12 09:35 UTC, merged